0:
  name: MainWindow
  type: MainWindow
1:
  name: Workspace
  type: Workspace
2:
  name: Editor
  positionInSceneCoords:
  - 2419.8960172857833
  - 1935.080925739754
  type: Editor
  zoom: 0.4785329583288633
3:
  linksIn: {}
  linksOut: {}
  name: EditorMenu
  size:
  - 350
  - 250
  type: EditorMenu
4:
  name: Global Lattice
  sceneHeight: 145
  sceneWidth: 1200
  type: Global Lattice
5:
  name: Inspector
  size:
  - 415
  - -1
  type: Inspector
6:
  alignment: Vertical
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Slider
      type: KickAngleComponent
      units: mrad
      value: 0
  linkedElement: 135
  linksIn: {}
  linksOut:
    32: corrector
  name: BS-PC-VSTR-06:SETI
  position:
  - 1813
  - 1701
  size:
  - 325
  - 75
  type: Corrector
7:
  alignment: Vertical
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Slider
      type: KickAngleComponent
      units: mrad
      value: 0
  linkedElement: 148
  linksIn: {}
  linksOut:
    32: corrector
  name: BS-PC-VSTR-07:SETI
  position:
  - 1813
  - 1782
  size:
  - 325
  - 75
  type: Corrector
8:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Slider
      type: KickAngleComponent
      units: mrad
      value: 0
  linkedElement: 133
  linksIn: {}
  linksOut:
    32: corrector
  name: BS-PC-HSTR-06:SETI
  position:
  - 1398
  - 1691
  size:
  - 325
  - 75
  type: Corrector
9:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Slider
      type: KickAngleComponent
      units: mrad
      value: 0
  linkedElement: 146
  linksIn: {}
  linksOut:
    32: corrector
  name: BS-PC-HSTR-07:SETI
  position:
  - 1400
  - 1772
  size:
  - 325
  - 75
  type: Corrector
10:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Slider
      type: KickAngleComponent
      units: mrad
      value: 0
  linkedElement: 117
  linksIn: {}
  linksOut:
    32: corrector
  name: BS-PC-HSTR-05:SETI
  position:
  - 1398
  - 1610
  size:
  - 325
  - 75
  type: Corrector
11:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Slider
      type: KickAngleComponent
      units: mrad
      value: 0
  linkedElement: 82
  linksIn: {}
  linksOut:
    32: corrector
  name: BS-PC-HSTR-04:SETI
  position:
  - 1398
  - 1530
  size:
  - 325
  - 75
  type: Corrector
12:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Slider
      type: KickAngleComponent
      units: mrad
      value: 0
  linkedElement: 66
  linksIn: {}
  linksOut:
    32: corrector
  name: BS-PC-HSTR-03:SETI
  position:
  - 1395
  - 1449
  size:
  - 325
  - 75
  type: Corrector
13:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Slider
      type: KickAngleComponent
      units: mrad
      value: 0
  linkedElement: 56
  linksIn: {}
  linksOut:
    32: corrector
  name: BS-PC-HSTR-02:SETI
  position:
  - 1400
  - 1368
  size:
  - 325
  - 75
  type: Corrector
14:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Slider
      type: KickAngleComponent
      units: mrad
      value: 0
  linkedElement: 42
  linksIn: {}
  linksOut:
    32: corrector
    33: decision
  name: BS-PC-HSTR-01:SETI
  position:
  - 1396
  - 1287
  size:
  - 325
  - 75
  type: Corrector
15:
  alignment: Vertical
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Slider
      type: KickAngleComponent
      units: mrad
      value: 0
  linkedElement: 44
  linksIn: {}
  linksOut:
    32: corrector
  name: BS-PC-VSTR-01:SETI
  position:
  - 1817
  - 1288
  size:
  - 325
  - 75
  type: Corrector
16:
  alignment: Vertical
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Slider
      type: KickAngleComponent
      units: mrad
      value: 0
  linkedElement: 58
  linksIn: {}
  linksOut:
    32: corrector
  name: BS-PC-VSTR-02:SETI
  position:
  - 1818
  - 1372
  size:
  - 325
  - 75
  type: Corrector
17:
  alignment: Vertical
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Slider
      type: KickAngleComponent
      units: mrad
      value: 0
  linkedElement: 68
  linksIn: {}
  linksOut:
    32: corrector
  name: BS-PC-VSTR-03:SETI
  position:
  - 1816
  - 1455
  size:
  - 325
  - 75
  type: Corrector
18:
  alignment: Vertical
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Slider
      type: KickAngleComponent
      units: mrad
      value: 0
  linkedElement: 84
  linksIn: {}
  linksOut:
    32: corrector
  name: BS-PC-VSTR-04:SETI
  position:
  - 1817
  - 1538
  size:
  - 325
  - 75
  type: Corrector
19:
  alignment: Vertical
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Slider
      type: KickAngleComponent
      units: mrad
      value: 0
  linkedElement: 119
  linksIn: {}
  linksOut:
    32: corrector
  name: BS-PC-VSTR-05:SETI
  position:
  - 1817
  - 1619
  size:
  - 325
  - 75
  type: Corrector
20:
  alignment: Vertical
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
  linkedElement: 60
  linksIn: {}
  linksOut:
    32: BPM
    33: objective
  name: BS-DI-EBPM-02:Y
  position:
  - 1814
  - 1949
  size:
  - 325
  - 75
  type: BPM
21:
  alignment: Vertical
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
  linkedElement: 140
  linksIn: {}
  linksOut:
    32: BPM
  name: BS-DI-EBPM-06:Y
  position:
  - 1809
  - 2274
  size:
  - 325
  - 75
  type: BPM
22:
  alignment: Vertical
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
  linkedElement: 76
  linksIn: {}
  linksOut:
    32: BPM
  name: BS-DI-EBPM-03:Y
  position:
  - 1813
  - 2031
  size:
  - 325
  - 75
  type: BPM
23:
  alignment: Vertical
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
  linkedElement: 111
  linksIn: {}
  linksOut:
    32: BPM
  name: BS-DI-EBPM-04:Y
  position:
  - 1812
  - 2113
  size:
  - 325
  - 75
  type: BPM
24:
  alignment: Vertical
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
  linkedElement: 127
  linksIn: {}
  linksOut:
    32: BPM
  name: BS-DI-EBPM-05:Y
  position:
  - 1811
  - 2194
  size:
  - 325
  - 75
  type: BPM
25:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
  linkedElement: 60
  linksIn: {}
  linksOut:
    32: BPM
  name: BS-DI-EBPM-02:X
  position:
  - 1394
  - 1938
  size:
  - 325
  - 75
  type: BPM
26:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
  linkedElement: 76
  linksIn: {}
  linksOut:
    32: BPM
  name: BS-DI-EBPM-03:X
  position:
  - 1396
  - 2020
  size:
  - 325
  - 75
  type: BPM
27:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
  linkedElement: 111
  linksIn: {}
  linksOut:
    32: BPM
  name: BS-DI-EBPM-04:X
  position:
  - 1394
  - 2101
  size:
  - 325
  - 75
  type: BPM
28:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
  linkedElement: 155
  linksIn: {}
  linksOut:
    32: BPM
  name: BS-DI-EBPM-07:X
  position:
  - 1389
  - 2345
  size:
  - 325
  - 75
  type: BPM
29:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
  linkedElement: 140
  linksIn: {}
  linksOut:
    32: BPM
  name: BS-DI-EBPM-06:X
  position:
  - 1389
  - 2264
  size:
  - 325
  - 75
  type: BPM
30:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
  linkedElement: 127
  linksIn: {}
  linksOut:
    32: BPM
  name: BS-DI-EBPM-05:X
  position:
  - 1391
  - 2183
  size:
  - 325
  - 75
  type: BPM
31:
  alignment: Vertical
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
  linkedElement: 155
  linksIn: {}
  linksOut:
    32: BPM
  name: BS-DI-EBPM-07:Y
  position:
  - 1808
  - 2355
  size:
  - 325
  - 75
  type: BPM
32:
  components:
    current:
      default: 0.5
      max: 5
      min: 0.01
      name: Current
      type: SliderComponent
      units: mrad
      value: 0.5
    repeats:
      default: 5
      max: 20
      min: 1
      name: Repeats
      type: SliderComponent
      units: ''
      value: 5
      valueType: int
    steps:
      default: 3
      max: 9
      min: 3
      name: Steps
      type: SliderComponent
      units: mrad
      value: 3
      valueType: int
  linksIn:
    6: corrector
    7: corrector
    8: corrector
    9: corrector
    10: corrector
    11: corrector
    12: corrector
    13: corrector
    14: corrector
    15: corrector
    16: corrector
    17: corrector
    18: corrector
    19: corrector
    20: BPM
    21: BPM
    22: BPM
    23: BPM
    24: BPM
    25: BPM
    26: BPM
    27: BPM
    28: BPM
    29: BPM
    30: BPM
    31: BPM
  linksOut:
    34: data
  name: Orbit Response
  position:
  - 2415
  - 1687
  size:
  - 575
  - 440
  type: Orbit Response
33:
  linksIn:
    14: decision
    20: objective
  linksOut:
    35: data
  name: Single Task GP
  position:
  - 2402
  - 1068
  size:
  - 600
  - 500
  type: Single Task GP
34:
  linksIn:
    32: data
  linksOut: {}
  name: View
  position:
  - 3269
  - 1693
  size:
  - 1000
  - 850
  type: View
35:
  linksIn:
    33: data
  linksOut: {}
  name: View
  position:
  - 3274
  - 740
  size:
  - 1000
  - 850
  type: View
