0:
  name: MainWindow
  type: MainWindow
1:
  name: Workspace
  type: Workspace
2:
  name: Editor
  positionInSceneCoords:
  - 2266.3686758891668
  - 1495.7464535981203
  type: Editor
  zoom: 0.3516638790850355
3:
  linksIn: {}
  linksOut: {}
  name: EditorMenu
  size:
  - 350
  - 250
  type: EditorMenu
4:
  name: Global Lattice
  sceneHeight: 145
  sceneWidth: 1200
  type: Global Lattice
5:
  name: Inspector
  size:
  - 415
  - -1
  type: Inspector
6:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
  linkedElement: 60
  linksIn: {}
  linksOut:
    8: BPM
  name: BS-DI-EBPM-02:FT:X
  position:
  - 957
  - 1892
  size:
  - 325
  - 75
  type: BPM
7:
  alignment: Vertical
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Slider
      type: KickAngleComponent
      units: mrad
      value: 0
  linkedElement: 44
  linksIn: {}
  linksOut:
    8: corrector
  name: BS-PC-VSTR-01:SETI:Y
  position:
  - 1337
  - 1245
  size:
  - 325
  - 75
  type: Corrector
8:
  components:
    current:
      default: 0.5
      max: 5
      min: 0.01
      name: Current
      type: SliderComponent
      units: mrad
      value: 0.5
    repeats:
      default: 5
      max: 20
      min: 1
      name: Repeats
      type: SliderComponent
      units: ''
      value: 5
      valueType: int
    steps:
      default: 3
      max: 9
      min: 3
      name: Steps
      type: SliderComponent
      units: mrad
      value: 3
      valueType: int
  linksIn:
    6: BPM
    7: corrector
    13: corrector
    14: corrector
    15: corrector
    16: corrector
    17: corrector
    18: corrector
    19: corrector
    20: corrector
    21: corrector
    22: corrector
    23: corrector
    24: corrector
    25: corrector
    26: BPM
    27: BPM
    28: BPM
    29: BPM
    30: BPM
    31: BPM
    32: BPM
    33: BPM
    34: BPM
    35: BPM
    36: BPM
  linksOut:
    12: data
  name: Orbit Response
  position:
  - 1889
  - 1695
  size:
  - 575
  - 440
  type: Orbit Response
9:
  linksIn: {}
  linksOut: {}
  name: View
  position:
  - 3273
  - 969
  size:
  - 600
  - 500
  type: View
10:
  alignment: Vertical
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Slider
      type: KickAngleComponent
      units: mrad
      value: 0
  linksIn: {}
  linksOut: {}
  name: BS-PC-VSTR-01:SETI
  position:
  - 2059
  - 1073
  size:
  - 325
  - 75
  type: Corrector
11:
  linksIn: {}
  linksOut: {}
  name: Single Task GP
  position:
  - 2577
  - 1110
  size:
  - 600
  - 500
  type: Single Task GP
12:
  linksIn:
    8: data
  linksOut: {}
  name: View
  position:
  - 2646
  - 1731
  size:
  - 600
  - 500
  type: View
13:
  alignment: Vertical
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Slider
      type: KickAngleComponent
      units: mrad
      value: 0
  linkedElement: 58
  linksIn: {}
  linksOut:
    8: corrector
  name: BS-PC-VSTR-02:SETI:Y
  position:
  - 1337
  - 1328
  size:
  - 325
  - 75
  type: Corrector
14:
  alignment: Vertical
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Slider
      type: KickAngleComponent
      units: mrad
      value: 0
  linkedElement: 68
  linksIn: {}
  linksOut:
    8: corrector
  name: BS-PC-VSTR-03:SETI:Y
  position:
  - 1339
  - 1410
  size:
  - 325
  - 75
  type: Corrector
15:
  alignment: Vertical
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Slider
      type: KickAngleComponent
      units: mrad
      value: 0
  linkedElement: 84
  linksIn: {}
  linksOut:
    8: corrector
  name: BS-PC-VSTR-04:SETI:Y
  position:
  - 1335
  - 1493
  size:
  - 325
  - 75
  type: Corrector
16:
  alignment: Vertical
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Slider
      type: KickAngleComponent
      units: mrad
      value: 0
  linkedElement: 119
  linksIn: {}
  linksOut:
    8: corrector
  name: BS-PC-VSTR-05:SETI:Y
  position:
  - 1338
  - 1574
  size:
  - 325
  - 75
  type: Corrector
17:
  alignment: Vertical
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Slider
      type: KickAngleComponent
      units: mrad
      value: 0
  linkedElement: 135
  linksIn: {}
  linksOut:
    8: corrector
  name: BS-PC-VSTR-06:SETI:Y
  position:
  - 1337
  - 1655
  size:
  - 325
  - 75
  type: Corrector
18:
  alignment: Vertical
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Slider
      type: KickAngleComponent
      units: mrad
      value: 0
  linkedElement: 148
  linksIn: {}
  linksOut:
    8: corrector
  name: BS-PC-VSTR-07:SETI:Y
  position:
  - 1333
  - 1734
  size:
  - 325
  - 75
  type: Corrector
19:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Slider
      type: KickAngleComponent
      units: mrad
      value: 0
  linkedElement: 42
  linksIn: {}
  linksOut:
    8: corrector
  name: BS-PC-HSTR-01:SETI:X
  position:
  - 956
  - 1246
  size:
  - 325
  - 75
  type: Corrector
20:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Slider
      type: KickAngleComponent
      units: mrad
      value: 0
  linkedElement: 56
  linksIn: {}
  linksOut:
    8: corrector
  name: BS-PC-HSTR-02:SETI:X
  position:
  - 957
  - 1330
  size:
  - 325
  - 75
  type: Corrector
21:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Slider
      type: KickAngleComponent
      units: mrad
      value: 0
  linkedElement: 66
  linksIn: {}
  linksOut:
    8: corrector
  name: BS-PC-HSTR-03:SETI:X
  position:
  - 956
  - 1413
  size:
  - 325
  - 75
  type: Corrector
22:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Slider
      type: KickAngleComponent
      units: mrad
      value: 0
  linkedElement: 82
  linksIn: {}
  linksOut:
    8: corrector
  name: BS-PC-HSTR-04:SETI:X
  position:
  - 958
  - 1496
  size:
  - 325
  - 75
  type: Corrector
23:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Slider
      type: KickAngleComponent
      units: mrad
      value: 0
  linkedElement: 117
  linksIn: {}
  linksOut:
    8: corrector
  name: BS-PC-HSTR-05:SETI:X
  position:
  - 960
  - 1577
  size:
  - 325
  - 75
  type: Corrector
24:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Slider
      type: KickAngleComponent
      units: mrad
      value: 0
  linkedElement: 133
  linksIn: {}
  linksOut:
    8: corrector
  name: BS-PC-HSTR-06:SETI:X
  position:
  - 959
  - 1660
  size:
  - 325
  - 75
  type: Corrector
25:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Slider
      type: KickAngleComponent
      units: mrad
      value: 0
  linkedElement: 146
  linksIn: {}
  linksOut:
    8: corrector
  name: BS-PC-HSTR-07:SETI:X
  position:
  - 956
  - 1742
  size:
  - 325
  - 75
  type: Corrector
26:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
  linkedElement: 76
  linksIn: {}
  linksOut:
    8: BPM
  name: BS-DI-EBPM-03:FT:X
  position:
  - 955
  - 1973
  size:
  - 325
  - 75
  type: BPM
27:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
  linkedElement: 140
  linksIn: {}
  linksOut:
    8: BPM
  name: BS-DI-EBPM-06:FT:X
  position:
  - 952
  - 2218
  size:
  - 325
  - 75
  type: BPM
28:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
  linkedElement: 155
  linksIn: {}
  linksOut:
    8: BPM
  name: BS-DI-EBPM-07:FT:X
  position:
  - 953
  - 2298
  size:
  - 325
  - 75
  type: BPM
29:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
  linkedElement: 127
  linksIn: {}
  linksOut:
    8: BPM
  name: BS-DI-EBPM-05:FT:X
  position:
  - 950
  - 2136
  size:
  - 325
  - 75
  type: BPM
30:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
  linkedElement: 111
  linksIn: {}
  linksOut:
    8: BPM
  name: BS-DI-EBPM-04:FT:X
  position:
  - 953
  - 2055
  size:
  - 325
  - 75
  type: BPM
31:
  alignment: Vertical
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
  linkedElement: 60
  linksIn: {}
  linksOut:
    8: BPM
  name: BS-DI-EBPM-02:FT:Y
  position:
  - 1339
  - 1893
  size:
  - 325
  - 75
  type: BPM
32:
  alignment: Vertical
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
  linkedElement: 127
  linksIn: {}
  linksOut:
    8: BPM
  name: BS-DI-EBPM-05:FT:Y
  position:
  - 1336
  - 2136
  size:
  - 325
  - 75
  type: BPM
33:
  alignment: Vertical
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
  linkedElement: 111
  linksIn: {}
  linksOut:
    8: BPM
  name: BS-DI-EBPM-04:FT:Y
  position:
  - 1338
  - 2056
  size:
  - 325
  - 75
  type: BPM
34:
  alignment: Vertical
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
  linkedElement: 140
  linksIn: {}
  linksOut:
    8: BPM
  name: BS-DI-EBPM-06:FT:Y
  position:
  - 1338
  - 2216
  size:
  - 325
  - 75
  type: BPM
35:
  alignment: Vertical
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
  linkedElement: 155
  linksIn: {}
  linksOut:
    8: BPM
  name: BS-DI-EBPM-07:FT:Y
  position:
  - 1333
  - 2297
  size:
  - 325
  - 75
  type: BPM
36:
  alignment: Vertical
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
  linkedElement: 76
  linksIn: {}
  linksOut:
    8: BPM
  name: BS-DI-EBPM-03:FT:Y
  position:
  - 1339
  - 1975
  size:
  - 325
  - 75
  type: BPM
