0:
  name: MainWindow
  type: MainWindow
1:
  name: Workspace
  type: Workspace
2:
  name: Editor
  positionInSceneCoords:
  - 2494.051722640623
  - 1710.8953846133743
  type: Editor
  zoom: 0.4979848608291931
3:
  linksIn: {}
  linksOut: {}
  name: EditorMenu
  size:
  - 350
  - 250
  type: EditorMenu
4:
  name: Global Lattice
  sceneHeight: 145
  sceneWidth: 1200
  type: Global Lattice
5:
  name: Inspector
  size:
  - 415
  - -1
  type: Inspector
6:
  alignment: Vertical
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Slider
      type: KickAngleComponent
      units: mrad
      value: 0
  linkedElement: 24
  linksIn: {}
  linksOut:
    8: corrector
  name: Corrector
  position:
  - 1502
  - 1591
  size:
  - 250
  - 75
  type: Corrector
7:
  alignment: Vertical
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
  linkedElement: 11
  linksIn: {}
  linksOut:
    8: BPM
  name: BPM
  position:
  - 1541
  - 1755
  size:
  - 250
  - 75
  type: BPM
8:
  components:
    current:
      default: 0.5
      max: 5
      min: 0.01
      name: Current
      type: SliderComponent
      units: mrad
      value: 0.5
    repeats:
      default: 5
      max: 20
      min: 1
      name: Repeats
      type: SliderComponent
      units: ''
      value: 5
      valueType: int
    steps:
      default: 3
      max: 9
      min: 3
      name: Steps
      type: SliderComponent
      units: mrad
      value: 3
      valueType: int
  linksIn:
    6: corrector
    7: BPM
  linksOut:
    9: data
  name: Orbit Response
  position:
  - 1943
  - 1546
  size:
  - 575
  - 440
  type: Orbit Response
9:
  linksIn:
    8: data
  linksOut: {}
  name: View
  position:
  - 2690.4680281656706
  - 1471.6768689037956
  size:
  - 600
  - 500
  type: View
