0:
  name: MainWindow
  type: MainWindow
1:
  name: Workspace
  type: Workspace
2:
  name: Editor
  positionInSceneCoords:
  - 2750.303550510835
  - 1283.7551332025364
  type: Editor
  zoom: 0.4759474639651573
3:
  linksIn: {}
  linksOut: {}
  name: EditorMenu
  size:
  - 250
  - 350
  type: EditorMenu
4:
  name: Global Lattice
  sceneHeight: 145
  sceneWidth: 1200
  type: Global Lattice
5:
  name: Inspector
  size:
  - 415
  - -1
  type: Inspector
6:
  alignment: Vertical
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Slider
      type: KickAngleComponent
      units: mrad
      value: 0
  linkedElement: 24
  linksIn: {}
  linksOut:
    7: corrector
    8: corrector
  name: Corrector
  position:
  - 1504
  - 1250
  size:
  - 225
  - 50
  type: Corrector
7:
  components:
    current:
      default: 0.5
      max: 5
      min: 0.01
      name: Current
      type: SliderComponent
      units: mrad
      value: 0.5
    repeats:
      default: 5
      max: 20
      min: 1
      name: Repeats
      type: SliderComponent
      units: ''
      value: 5
      valueType: int
    steps:
      default: 3
      max: 9
      min: 3
      name: Steps
      type: SliderComponent
      units: mrad
      value: 3
      valueType: int
  linksIn:
    6: corrector
    9: BPM
  linksOut:
    10: data
  name: Orbit Response
  position:
  - 2093
  - 872
  size:
  - 550
  - 440
  type: Orbit Response
8:
  components:
    current:
      default: 0.5
      max: 5
      min: 0.01
      name: Current
      type: SliderComponent
      units: mrad
      value: 0.5
    repeats:
      default: 5
      max: 20
      min: 1
      name: Repeats
      type: SliderComponent
      units: ''
      value: 5
      valueType: int
    steps:
      default: 3
      max: 9
      min: 3
      name: Steps
      type: SliderComponent
      units: mrad
      value: 3
      valueType: int
  linksIn:
    6: corrector
    9: BPM
  linksOut:
    11: data
  name: Orbit Response
  position:
  - 2095
  - 1369
  size:
  - 550
  - 440
  type: Orbit Response
9:
  alignment: Vertical
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
  linkedElement: 11
  linksIn: {}
  linksOut:
    7: BPM
    8: BPM
  name: BPM
  position:
  - 1504
  - 1358
  size:
  - 225
  - 50
  type: BPM
10:
  linksIn:
    7: data
  linksOut: {}
  name: View
  position:
  - 2825
  - 764
  size:
  - 600
  - 500
  type: View
11:
  linksIn:
    8: data
  linksOut: {}
  name: View
  position:
  - 2820.0
  - 1406.0
  size:
  - 600
  - 500
  type: View
