0:
  name: MainWindow
  type: MainWindow
1:
  name: Workspace
  type: Workspace
2:
  name: Editor
  positionInSceneCoords:
  - 3537.7410176057674
  - 2573.8230299810707
  type: Editor
  zoom: 0.4938179452102221
3:
  linksIn: {}
  linksOut: {}
  name: EditorMenu
  size:
  - 350
  - 250
  type: EditorMenu
4:
  name: Global Lattice
  sceneHeight: 145
  sceneWidth: 1200
  type: Global Lattice
5:
  name: Inspector
  size:
  - 415
  - -1
  type: Inspector
6:
  linksIn:
    7: decision
  linksOut:
    16: data
  name: Single Task GP
  position:
  - 3196
  - 1670
  size:
  - 600
  - 500
  type: Single Task GP
7:
  components:
    truncation:
      default: 5
      max: 5
      min: 1
      name: truncation
      type: SliderComponent
      units: ''
      value: 4
      valueType: int
  linksIn:
    32: in
  linksOut:
    6: decision
    15: data
    34: data
  name: SVD
  position:
  - 2528
  - 2026
  size:
  - 500
  - 200
  type: SVD
10:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0.0
      max: 5.0
      min: -5.0
      name: Slider
      type: KickAngleComponent
      units: mrad
      value: 0.0
      valueType: float
  linkedElement: 117
  linksIn: {}
  linksOut:
    32: corrector
  name: BS-PC-HSTR-05:SETI
  position:
  - 1398
  - 1610
  size:
  - 325
  - 75
  type: Corrector
11:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0.0
      max: 5.0
      min: -5.0
      name: Slider
      type: KickAngleComponent
      units: mrad
      value: 0.0
      valueType: float
  linkedElement: 82
  linksIn: {}
  linksOut:
    32: corrector
  name: BS-PC-HSTR-04:SETI
  position:
  - 1398
  - 1530
  size:
  - 325
  - 75
  type: Corrector
12:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0.0
      max: 5.0
      min: -5.0
      name: Slider
      type: KickAngleComponent
      units: mrad
      value: 0.0
      valueType: float
  linkedElement: 66
  linksIn: {}
  linksOut:
    32: corrector
  name: BS-PC-HSTR-03:SETI
  position:
  - 1395
  - 1451
  size:
  - 325
  - 75
  type: Corrector
13:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0.0
      max: 5.0
      min: -5.0
      name: Slider
      type: KickAngleComponent
      units: mrad
      value: 0.0
      valueType: float
  linkedElement: 56
  linksIn: {}
  linksOut:
    32: corrector
  name: BS-PC-HSTR-02:SETI
  position:
  - 1400
  - 1368
  size:
  - 325
  - 75
  type: Corrector
14:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0.0
      max: 5.0
      min: -5.0
      name: Kick
      type: KickAngleComponent
      units: mrad
      value: 0.0009999999999994458
      valueType: float
  linkedElement: 42
  linksIn: {}
  linksOut:
    32: corrector
  name: BS-PC-HSTR-01:SETI
  position:
  - 1396
  - 1287
  size:
  - 325
  - 75
  type: Corrector
15:
  linksIn:
    7: data
  linksOut: {}
  name: View
  position:
  - 2733
  - 2279
  size:
  - 1000
  - 850
  type: View
16:
  linksIn:
    6: data
  linksOut: {}
  name: View
  position:
  - 4130
  - 1279
  size:
  - 1000
  - 850
  type: View
25:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
  linkedElement: 60
  linksIn: {}
  linksOut:
    32: BPM
  name: BS-DI-EBPM-02:X
  position:
  - 1394
  - 1938
  size:
  - 325
  - 75
  type: BPM
26:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
  linkedElement: 76
  linksIn: {}
  linksOut:
    32: BPM
  name: BS-DI-EBPM-03:X
  position:
  - 1396
  - 2020
  size:
  - 325
  - 75
  type: BPM
27:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
  linkedElement: 111
  linksIn: {}
  linksOut:
    32: BPM
  name: BS-DI-EBPM-04:X
  position:
  - 1394
  - 2101
  size:
  - 325
  - 75
  type: BPM
28:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
  linkedElement: 155
  linksIn: {}
  linksOut:
    32: BPM
  name: BS-DI-EBPM-07:X
  position:
  - 1389
  - 2345
  size:
  - 325
  - 75
  type: BPM
30:
  alignment: Horizontal
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
  linkedElement: 127
  linksIn: {}
  linksOut:
    32: BPM
  name: BS-DI-EBPM-05:X
  position:
  - 1391
  - 2183
  size:
  - 325
  - 75
  type: BPM
32:
  components:
    current:
      default: 0.5
      max: 5
      min: 0.01
      name: Current
      type: SliderComponent
      units: mrad
      value: 0.5
    repeats:
      default: 5
      max: 20
      min: 1
      name: Repeats
      type: SliderComponent
      units: ''
      value: 1
      valueType: int
    steps:
      default: 3
      max: 9
      min: 3
      name: Steps
      type: SliderComponent
      units: mrad
      value: 3
      valueType: int
  linksIn:
    10: corrector
    11: corrector
    12: corrector
    13: corrector
    14: corrector
    25: BPM
    26: BPM
    27: BPM
    28: BPM
    30: BPM
  linksOut:
    7: in
    47: data
  name: Orbit Response
  position:
  - 1914
  - 1530
  size:
  - 575
  - 440
  type: Orbit Response
34:
  linksIn:
    7: data
  linksOut: {}
  name: View
  position:
  - 3754
  - 2283
  size:
  - 1000
  - 850
  type: View
47:
  linksIn:
    32: data
  linksOut: {}
  name: View
  position:
  - 2047
  - 589
  size:
  - 1000
  - 850
  type: View
