0:
  name: MainWindow
  type: MainWindow
1:
  name: Workspace
  type: Workspace
2:
  name: Editor
  positionInSceneCoords:
  - 2727.0338039745634
  - 2265.267696592289
  type: Editor
  zoom: 0.45910688682159007
3:
  linksIn: {}
  linksOut: {}
  name: EditorMenu
  size:
  - 350
  - 250
  type: EditorMenu
4:
  name: Global Lattice
  sceneHeight: 145
  sceneWidth: 1200
  type: Global Lattice
5:
  name: Inspector
  size:
  - 415
  - -1
  type: Inspector
6:
  alignment: Vertical
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
  linkedElement: 11
  linksIn: {}
  linksOut:
    8: BPM
  name: BPM
  position:
  - 1482
  - 1743
  size:
  - 325
  - 75
  type: BPM
7:
  alignment: Vertical
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Slider
      type: KickAngleComponent
      units: mrad
      value: 0
  linkedElement: 24
  linksIn: {}
  linksOut:
    8: corrector
  name: This is so freakin' kewl
  position:
  - 1364
  - 1531
  size:
  - 325
  - 75
  type: Corrector
8:
  components:
    current:
      default: 0.5
      max: 5
      min: 0.01
      name: Current
      type: SliderComponent
      units: mrad
      value: 0.5
    repeats:
      default: 5
      max: 20
      min: 1
      name: Repeats
      type: SliderComponent
      units: ''
      value: 5
      valueType: int
    steps:
      default: 3
      max: 9
      min: 3
      name: Steps
      type: SliderComponent
      units: mrad
      value: 3
      valueType: int
  linksIn:
    6: BPM
    7: corrector
  linksOut:
    10: data
  name: Orbit Response
  position:
  - 1878
  - 1345
  size:
  - 575
  - 440
  type: Orbit Response
9:
  linksIn:
    11: data
  linksOut: {}
  name: View
  position:
  - 2677.0
  - 2235.0
  size:
  - 600
  - 500
  type: View
10:
  linksIn:
    8: data
  linksOut: {}
  name: View
  position:
  - 2612
  - 1257
  size:
  - 600
  - 500
  type: View
11:
  linksIn:
    12: decision
    13: objective
  linksOut:
    9: data
  name: Single Task GP
  position:
  - 1959
  - 2029
  size:
  - 600
  - 500
  type: Single Task GP
12:
  alignment: Vertical
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
    value:
      default: 0
      max: 100
      min: 0
      name: Slider
      type: KickAngleComponent
      units: mrad
      value: 0
  linkedElement: 24
  linksIn: {}
  linksOut:
    11: decision
  name: Corrector
  position:
  - 1491
  - 2184
  size:
  - 325
  - 75
  type: Corrector
13:
  alignment: Vertical
  components:
    linkedLatticeElement:
      name: Linked Lattice Element
      type: LinkComponent
  linkedElement: 11
  linksIn: {}
  linksOut:
    11: objective
  name: BPM
  position:
  - 1496
  - 2353
  size:
  - 325
  - 75
  type: BPM
